### ISSUE TITLE
can't open the installed apk

### ISSUE THREAD

**Issue by idontveapc** [TESLA2402/Supabase_Flutter#20]

**Comment by TESLA2402** [comment]
Hello, @idontveapc, thank you for bringing up the issue. I appreciate your input. However, I would like to mention that it is working fine for me. Could you please provide more details about the device you are using? Specifically, is it a Samsung device? Your additional information will help me investigate the issue more thoroughly.

**Comment by TESLA2402** [comment]
Hey! @idontveapc can you try it now it should

**Comment by TESLA2402** [comment]
Hello @idontveapc, could you please check again? Everything should be working smoothly now. The project was temporarily paused from the Supabase side. Kindly confirm if it is functioning properly for you. Thank you.

**Comment by TESLA2402** [comment]
Hello! @idontveapc has successfully resolved the issue. The app should now be installing without any issues. Please confirm if it is functioning correctly for you. Thank you.

**Comment by TESLA2402** [comment]
Hello, @idontveapc! Please inform me if everything is working fine for you now.

**Comment by TESLA2402** [comment]
Yup! the above reported issue has been resolved, and after thorough testing on emulators and real devices, the updated release is confirmed to be working seamlessly. Please install the new release and let me know if the problem persists on your end. 
Thank you
