### ISSUE TITLE
release apk(s) for cpu arch(s), not in one apk...

### ISSUE THREAD

**Issue by idontveapc** [TESLA2402/Supabase_Flutter#33]
it overall takes enough storage for me, knowing it could l
take lesser.

**Comment by TESLA2402** [comment]
Hey! @idontveapc 
Can you please specify the CPU arch apk that you need?
Is it one of them?
app-arm64-v8a-release.apk
app-armeabi-v7a-release.apk
app-x86_64.apk

**Comment by TESLA2402** [comment]
Hey! @idontveapc  You can checkout the latest release and update me if it's working fine. I will close the issue once you verify.
